name: iot_starter_kit_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+900

environment:
  sdk: ">=2.12.0 <3.7.12"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  file: ^6.1.4
  url_launcher: ^6.0.9
  package_info_plus: ^1.3.0
  theme_provider: ^0.5.0
  pref: ^2.4.0
  get_it: ^7.1.3
  rxdart: ^0.27.1
  logger: ^1.0.0
  timeago: ^3.1.0
  fluttertoast: ^8.0.7
  fl_chart: ^0.36.2
  uuid: ^3.0.4
  mqtt_client: ^9.3.2
  auto_size_text: ^3.0.0-nullsafety.0
  about: ^2.0.1
  duration: ^3.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.1
  # A command-line tool that makes it trivial to set the launcher name for iOS and Android
  # Flutter apps. Works with Flutter 2.
  # details here: https://pub.dev/packages/flutter_app_name
  # Usage: update the app name in "flutter_app_name" setting and run this command
  # in your project's directory
  # >flutter pub get
  # >flutter pub run flutter_app_name

  flutter_launcher_icons: ^0.9.0

flutter_app_name:
  name: "IoT Starter Kit"

# run the following command ot update the icons:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  image_path_ios: "assets/logo/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/logo/

    # .md files for about screen
    - assets/docs/

    # translation files
    - locales/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
